### ISSUE TITLE
최신 버전에서 크롤링이 안됩니다.

### ISSUE THREAD

**Issue by pilos011** [yms2772/linux_manga_show_me_crawling#1]
재미있는 크롤러를 만들어 주셔서 고맙습니다.

제 리눅스머신에서 돌려보았는데, 잘 실행되었다고 하고 실제로 폴더에 가보면 아무 파일도 없어도
로그라도 있으면 짐작을 해볼텐데 답답해서 글을 오려보았습니다.

시간이 되시면 확인 부탁드립니다. 
- 망가쇼미 사이트가 느려서 그럴 수도 있겠다 싶은데, 느려도 착실히 진행될 수 있도록 하면 더 좋을 것 같아요.

**Comment by yms2772** [comment]
죄송합니다 현재 만화검색과 만화목록 페이지의 소스가 변경되어 크롤링이 안되는게 확인되었습니다.
현재 오류를 수정하고있습니다.

**Comment by yms2772** [comment]
모든 오류 수정했습니다.
